name: Docker Deploy

on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    if: >
      github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'workflow_dispatch'
    environment: DiscoEnv
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/discoflix:latest

      - name: Notify Discord
        if: success()
        run: |
          COMMIT_SHA_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
          curl -H "Content-Type: application/json" \
                -d '{
                      "embeds": [{
                        "title": "DiscoFlix has been updated!",
                        "description": "The latest Docker images for DiscoFlix have been successfully built and pushed. Please update your containers to the latest version.",
                        "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}",
                        "color": 5814783,
                        "fields": [
                          {
                            "name": "Commit",
                            "value": "[`'"$COMMIT_SHA_SHORT"'`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
                          }
                        ],
                        "image": {
                          "url": "https://i.imgur.com/wMhrFuq.png"
                        },
                        "footer": {
                          "text": "DiscoFlix Deployment"
                        }
                      }]
                    }' \
                ${{ secrets.DISCORD_WEBHOOK_URL }}
